# https://taskfile.dev

version: '3'

tasks:
  gen:
    cmds:
      - protoc -I proto -I . -I ${GOPATH}/src -I ${GOPATH}/src/github.com/envoyproxy/protoc-gen-validate --go_out=proto --go_opt=paths=source_relative --go-grpc_out=proto --go-grpc_opt=paths=source_relative --validate_out="lang=go:proto" --grpc-gateway_out proto --grpc-gateway_opt logtostderr=true --grpc-gateway_opt paths=source_relative  --grpc-gateway_opt generate_unbound_methods=true --openapiv2_out docs --openapiv2_opt logtostderr=true --openapiv2_opt generate_unbound_methods=true proto/*.proto
      - docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i /local/docs/link.swagger.json -l html2 -o /local/docs

#  protoc -I .
#  proto/*.proto
  http:
    cmds:
      - go build .
      - ./go-linkshort http

  main:
    cmds:
      - go build .
      - ./go-linkshort main

  gen-schema:
    cmds:
      # wipe existing generated code
      - find ./ent -not -path "./ent/schema*" -not -path "./ent" -delete
      # generate code
      - go run entgo.io/ent/cmd/ent generate ./ent/schema

  execute-migration:
    cmds:
      - go build .
      - ./go-linkshort execute-migration

  generate-migration:
    cmds:
      - go build .
      - ./supernova generate-migration
      - go generate ./ent

  validate-migration:
    cmds:
      - ./atlas-linux-amd64 migrate validate migrations

  rehash-migration:
    cmds:
      - ./atlas-linux-amd64 migrate hash --force