// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/alexgtn/go-linkshort/ent/link"
	"github.com/alexgtn/go-linkshort/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	linkFields := schema.Link{}.Fields()
	_ = linkFields
	// linkDescLongURI is the schema descriptor for long_uri field.
	linkDescLongURI := linkFields[0].Descriptor()
	// link.LongURIValidator is a validator for the "long_uri" field. It is called by the builders before save.
	link.LongURIValidator = linkDescLongURI.Validators[0].(func(string) error)
	// linkDescAccessedTimes is the schema descriptor for accessed_times field.
	linkDescAccessedTimes := linkFields[1].Descriptor()
	// link.DefaultAccessedTimes holds the default value on creation for the accessed_times field.
	link.DefaultAccessedTimes = linkDescAccessedTimes.Default.(int)
	// link.AccessedTimesValidator is a validator for the "accessed_times" field. It is called by the builders before save.
	link.AccessedTimesValidator = linkDescAccessedTimes.Validators[0].(func(int) error)
	// linkDescCreatedAt is the schema descriptor for created_at field.
	linkDescCreatedAt := linkFields[2].Descriptor()
	// link.DefaultCreatedAt holds the default value on creation for the created_at field.
	link.DefaultCreatedAt = linkDescCreatedAt.Default.(func() time.Time)
	// linkDescUpdatedAt is the schema descriptor for updated_at field.
	linkDescUpdatedAt := linkFields[3].Descriptor()
	// link.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	link.DefaultUpdatedAt = linkDescUpdatedAt.Default.(func() time.Time)
	// link.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	link.UpdateDefaultUpdatedAt = linkDescUpdatedAt.UpdateDefault.(func() time.Time)
}
